version: '3.7'

services:
  nginx:
    image: nginx:1.19.2-alpine
    networks:
      net: {}
      promoth:
        aliases:
          - app_nginx
    ports:
      - 3050:80
    depends_on:
      - php
    volumes:
      - ./:/usr/share/nginx/html
    secrets:
      - source: conf
        target: /etc/nginx/conf.d/default.conf
#      - source: ssl_cert
#        target: /etc/nginx/ssl_certs/cert.pem
#      - source: ssl_key
#        target: /etc/nginx/ssl_certs/key.pem

  php:
    build:
      context: .
      dockerfile: docker/php/local.Dockerfile
    networks:
      - net
    environment:
      - COMPOSER_CACHE_DIR=/usr/share/nginx/html/storage/cache/.composer
    volumes:
      - ./:/usr/share/nginx/html

  redis:
    image: redis:5-alpine
    networks:
      - net

volumes:
  db: { }

networks:
  net: { }
  promoth:
    external: true
    name: promoth

secrets:
  conf:
    file: ./docker/nginx/nginx.conf
#  ssl_cert:
#    file: ./docker/certs/cert.pem
#  ssl_key:
#    file: ./docker/certs/key.pem
